// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6R1aia8B6JvOaBvZtJ6wAFirEAOX6-c',
    appId: '1:731138489751:web:393e00ede94fca891498d2',
    messagingSenderId: '731138489751',
    projectId: 'timed-3b4ac',
    authDomain: 'timed-3b4ac.firebaseapp.com',
    storageBucket: 'timed-3b4ac.appspot.com',
    measurementId: 'G-6W3QFLYRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0pGf7SmThSESxMpws8rOh9rRAZ5HQNw',
    appId: '1:731138489751:android:acd22853cf7f73ff1498d2',
    messagingSenderId: '731138489751',
    projectId: 'timed-3b4ac',
    storageBucket: 'timed-3b4ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptzA_yXrRVlobUcH9itecHv0PpwXs8SE',
    appId: '1:731138489751:ios:6a7bde5028aa6f551498d2',
    messagingSenderId: '731138489751',
    projectId: 'timed-3b4ac',
    storageBucket: 'timed-3b4ac.appspot.com',
    iosBundleId: 'com.example.timed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptzA_yXrRVlobUcH9itecHv0PpwXs8SE',
    appId: '1:731138489751:ios:6a7bde5028aa6f551498d2',
    messagingSenderId: '731138489751',
    projectId: 'timed-3b4ac',
    storageBucket: 'timed-3b4ac.appspot.com',
    iosBundleId: 'com.example.timed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa6R1aia8B6JvOaBvZtJ6wAFirEAOX6-c',
    appId: '1:731138489751:web:7f741b73b192c9461498d2',
    messagingSenderId: '731138489751',
    projectId: 'timed-3b4ac',
    authDomain: 'timed-3b4ac.firebaseapp.com',
    storageBucket: 'timed-3b4ac.appspot.com',
    measurementId: 'G-8EYJKLT84Q',
  );
}
